### ISSUE TITLE
0.12.md中图5-3 、图0-4 看不见了，麻烦郝大更新下，谢谢

### ISSUE THREAD

**Issue by salanhess** [hyper0x/go_command_tutorial#33]
https://github.com/hyper0x/go_command_tutorial/blob/master/0.12.md
中图5-3 、图0-4 看不见了，麻烦郝大更新下，谢谢
=========
 1. 在运行着图形界面软件的Linux操作系统下，会弹出这样一个窗口。如图5-3。
pprof工具的gv命令的执行结果

2. 从命令输出的提示信息可以看出，实际上callgrind命令把统计文件保存到了Linux的临时文件夹/tmp中。然后使用kcachegrind工具进行查看。下图为在pprof工具交互模式下执行callgrind命令后弹出的kcachegrind工具界面。
使用kcachegrind工具查看概要数据
图0-4 使用kcachegrind工具查看概要数据

**Comment by hyper0x** [comment]
应该是网络的问题，我这里可以看到。你懂的。
