### ISSUE TITLE
请教大神一个pprof分析内存（inuse_space）占用的问题,为什么会是负数

### ISSUE THREAD

**Issue by qifengzhang007** [hyper0x/go_command_tutorial#36]
我使用的命令：
go tool pprof -inuse_space  http://127.0.0.1:20191/debug/pprof/heap?seconds=10

遇到的问题：
inuse_space   怎么都是负数？该怎么理解？

![内存分析1](http://139.196.101.31:2080/images/question1.png)  

![内存分析1](http://139.196.101.31:2080/images/question1.png)  

如果以上图片无法查看，请直接单击图片地址查看：
http://139.196.101.31:2080/images/question1.png
http://139.196.101.31:2080/images/question2.png

**Comment by hyper0x** [comment]
你最好生成文件，使用debug=2，然后看看文件里的记录。到GoHackers的QQ群里（361287127）讨论吧。
